### PR TITLE
Burgess speedup

### PR DESCRIPTION
**Pull request by dstansby**
This on top of #69 speeds up level calculation for me by ~10x.

This PR removes `np.vectorize`, which doesn't provide significant speedup, but is provided for nicer code. Instead, where caclulations depend on only `scaling_type`, do these calculations on arrays for the speed up. This has the side effect of making it more obvious in the code which lines are slow (ie. the for loop where the spline interpolation is done).

### CODE REVIEW

**Comment by wtbarnes** [comment]
This looks great! I've been trying to think about how best to speed this up. I need to wrap my head around what this is actually doing first...

**Comment by wtbarnes** [comment]
Would you mind adding a test just checks that the vectorized and the normal version give the same result? 😁

**Comment by wtbarnes** [comment]
For some reason your new test wasn't getting picked up when the tests were running on travis? Presumably this is why the coverage went down, despite adding a test 😄

**Comment by fluxtransport** [comment]
Hi @dstansby thanks for working on speeding up the calculation. I'm having a problem with running the code but don't understand what exactly is the error. But it seems to happen after I pulled the latest version following this merge. 
Thanks in advance for any help. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-74c78731ca1c> in <module>
      2 # it has to solve a 337 by 337 matrix. This is the bottleneck of essentially the entire package
      3 # so speeding up that calculation would be a huge advantage.
----> 4 g=fe18.contribution_function(density)

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/util/decorators.py in func_wrapper(*args, **kwargs)
     20                 return default
     21             else:
---> 22                 return func(*args, **kwargs)
     23         return func_wrapper
     24     return decorator

~/anaconda3/lib/python3.7/site-packages/astropy/units/decorators.py in wrapper(*func_args, **func_kwargs)
    232             # Call the original function with any equivalencies in force.
    233             with add_enabled_equivalencies(self.equivalencies):
--> 234                 return_ = wrapped_function(*func_args, **func_kwargs)
    235             if wrapped_signature.return_annotation not in (inspect.Signature.empty, None):
    236                 return return_.to(wrapped_signature.return_annotation)

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/ion.py in contribution_function(self, density, **kwargs)
    362         """
    363         print(density)
--> 364         populations = self.level_populations(density, **kwargs)
    365         term = np.outer(self.ioneq, 1./density) * self.abundance * 0.83
    366         # Exclude two-photon transitions

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/util/decorators.py in func_wrapper(*args, **kwargs)
     20                 return default
     21             else:
---> 22                 return func(*args, **kwargs)
     23         return func_wrapper
     24     return decorator

~/anaconda3/lib/python3.7/site-packages/astropy/units/decorators.py in wrapper(*func_args, **func_kwargs)
    232             # Call the original function with any equivalencies in force.
    233             with add_enabled_equivalencies(self.equivalencies):
--> 234                 return_ = wrapped_function(*func_args, **func_kwargs)
    235             if wrapped_signature.return_annotation not in (inspect.Signature.empty, None):
    236                 return return_.to(wrapped_signature.return_annotation)

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/ion.py in level_populations(self, density, include_protons)
    276 
    277         # Collisional--electrons
--> 278         ex_rate_e = self.electron_collision_excitation_rate()
    279         dex_rate_e = self.electron_collision_deexcitation_rate()
    280         ex_diagonal_e = vectorize_where_sum(

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/util/decorators.py in func_wrapper(*args, **kwargs)
     20                 return default
     21             else:
---> 22                 return func(*args, **kwargs)
     23         return func_wrapper
     24     return decorator

~/anaconda3/lib/python3.7/site-packages/astropy/units/decorators.py in wrapper(*func_args, **func_kwargs)
    232             # Call the original function with any equivalencies in force.
    233             with add_enabled_equivalencies(self.equivalencies):
--> 234                 return_ = wrapped_function(*func_args, **func_kwargs)
    235             if wrapped_signature.return_annotation not in (inspect.Signature.empty, None):
    236                 return return_.to(wrapped_signature.return_annotation)

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/ion.py in electron_collision_excitation_rate(self)
    208         electron_collision_deexcitation_rate : De-excitation rate due to collisions
    209         """
--> 210         dex_rate = self.electron_collision_deexcitation_rate()
    211         omega_upper = 2. * self._elvlc['J'][self._scups['upper_level'] - 1] + 1.
    212         omega_lower = 2. * self._elvlc['J'][self._scups['lower_level'] - 1] + 1.

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/util/decorators.py in func_wrapper(*args, **kwargs)
     20                 return default
     21             else:
---> 22                 return func(*args, **kwargs)
     23         return func_wrapper
     24     return decorator

~/anaconda3/lib/python3.7/site-packages/astropy/units/decorators.py in wrapper(*func_args, **func_kwargs)
    232             # Call the original function with any equivalencies in force.
    233             with add_enabled_equivalencies(self.equivalencies):
--> 234                 return_ = wrapped_function(*func_args, **func_kwargs)
    235             if wrapped_signature.return_annotation not in (inspect.Signature.empty, None):
    236                 return return_.to(wrapped_signature.return_annotation)

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/ion.py in electron_collision_deexcitation_rate(self)
    194         """
    195         c = (const.h**2)/((2. * np.pi * const.m_e)**(1.5) * np.sqrt(const.k_B))
--> 196         upsilon = self.effective_collision_strength()
    197         omega_upper = 2. * self._elvlc['J'][self._scups['upper_level'] - 1] + 1.
    198         return c * upsilon / np.sqrt(self.temperature[:, np.newaxis]) / omega_upper

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/util/decorators.py in func_wrapper(*args, **kwargs)
     20                 return default
     21             else:
---> 22                 return func(*args, **kwargs)
     23         return func_wrapper
     24     return decorator

~/anaconda3/lib/python3.7/site-packages/astropy/units/decorators.py in wrapper(*func_args, **func_kwargs)
    232             # Call the original function with any equivalencies in force.
    233             with add_enabled_equivalencies(self.equivalencies):
--> 234                 return_ = wrapped_function(*func_args, **func_kwargs)
    235             if wrapped_signature.return_annotation not in (inspect.Signature.empty, None):
    236                 return return_.to(wrapped_signature.return_annotation)

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/ion.py in effective_collision_strength(self)
    162                                                   kBTE.T,
    163                                                   self._scups['bt_c'],
--> 164                                                   self._scups['bt_type'])
    165         upsilon = u.Quantity(np.where(upsilon > 0., upsilon, 0.))
    166         return upsilon.T

~/anaconda3/lib/python3.7/site-packages/fiasco-0.1.dev292-py3.7.egg/fiasco/util/tools.py in burgess_tully_descale_vectorize(x, y, energy_ratio, c, scaling_type)
    131     # Use list(map()) here to allow varying shaped inputs for x, y
    132     splrep_szero = partial(splrep, s=0)
--> 133     nots = np.array(list(map(splrep_szero, x, y)))
    134     splev_derzero = partial(splev, der=0)
    135     out = np.array(list(map(splev_derzero, xnew, nots)))

~/anaconda3/lib/python3.7/site-packages/scipy/interpolate/fitpack.py in splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
    287 
    288     """
--> 289     res = _impl.splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
    290     return res
    291 

~/anaconda3/lib/python3.7/site-packages/scipy/interpolate/_fitpack_impl.py in splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
    500     if not per:
    501         n, c, fp, ier = dfitpack.curfit(task, x, y, w, t, wrk, iwrk,
--> 502                                         xb, xe, k, s)
    503     else:
    504         n, c, fp, ier = dfitpack.percur(task, x, y, w, t, wrk, iwrk, k, s)

ValueError: setting an array element with a sequence.

**Comment by wtbarnes** [comment]
I can reproduce this and I've created a new issue to track it. See #77

**Pull request merged**
