### PR TITLE
Allow scalar density to level_populations

### LINKED ISSUE #56: Allow scalar density input to ion.level_populations?
Currently doing something like `ion.level_populations(5e8 * u.cm**-3)` errors with
```python
----> 1 ions[0].level_populations(5e8 * u.cm**-3)

~/github/fiasco/fiasco/util/decorators.py in func_wrapper(*args, **kwargs)
     20                 return default
     21             else:
---> 22                 return func(*args, **kwargs)
     23         return func_wrapper
     24     return decorator

~/miniconda3/lib/python3.8/site-packages/astropy/units/decorators.py in wrapper(*func_args, **func_kwargs)
    232             # Call the original function with any equivalencies in force.
    233             with add_enabled_equivalencies(self.equivalencies):
--> 234                 return_ = wrapped_function(*func_args, **func_kwargs)
    235             if wrapped_signature.return_annotation not in (inspect.Signature.empty, None):
    236                 return return_.to(wrapped_signature.return_annotation)

~/github/fiasco/fiasco/ion.py in level_populations(self, density, include_protons)
    290         # Populate density dependent terms and solve matrix equation for each density value
    291         populations = np.zeros(self.temperature.shape + density.shape + (level.max(),))
--> 292         for i, d in enumerate(density):
    293             c_matrix = coeff_matrix.copy()
    294             # Collisional excitation and de-excitation out of current state

~/miniconda3/lib/python3.8/site-packages/astropy/units/quantity.py in __iter__(self)
   1017     def __iter__(self):
   1018         if self.isscalar:
-> 1019             raise TypeError(
   1020                 "'{cls}' object with a scalar value is not iterable"
   1021                 .format(cls=self.__class__.__name__))

TypeError: 'Quantity' object with a scalar value is not iterable
```

I think this is just a case of making sure a scalar input is broadcast to at least 1D so that the for loop works.

### PR DESCRIPTION
**Pull request by dstansby**
Fixes #56

### CODE REVIEW

**Comment by wtbarnes** [comment]
Thanks! Would you be willing to add a test here too? Just something as simple as doing the level populations given a scalar density and checking that the shape of the resulting matrix is as expected. I've found that 0 II is a good test ion as it is quick to compute. The Fe ones are all quite slow.

No worries if you don't have the time. I'm happy to merge this as is.

**Comment by dstansby** [comment]
Yep, will add a test

**Comment by wtbarnes** [comment]
Might want to wait until #65 is merged and do a rebase before adding a test. I refactored the tests a bit.

**Comment by wtbarnes** [comment]
I made your density test check the resulting shape of the level populations explicitly and separated out the test for the scalar temperature.

**Comment by wtbarnes** [comment]
Ah sorry, Because my commit was the last one and I squash-merged, it looks like you don't show up in the commit history at all for this PR 🤦‍♂ 

I'm not sure the best way to go about preserving authorship when squash merging, but I'll be more careful about this in the future.

**Pull request merged**
