### PR TITLE
Verify hashes of files used for testing

### PR DESCRIPTION
**Pull request by dstansby**
This should check that the files being used/downloaded for testing are exactly as expected.

### CODE REVIEW

**Comment by dstansby** [comment]
I think this has worked as expected! I have Chianti 8.0.6 locally, which I generated the hashes with, but the tests expect 8.0.7, so this failed. Will update the hashes to 8.0.7 in a new commit.

**Comment by dstansby** [comment]
I think this has worked as expected! I have Chianti 8.0.6 locally, which I generated the hashes with, but the tests expect 8.0.7, so this failed. Will update the hashes to 8.0.7 in a new commit.

**Comment by wtbarnes** [comment]
This is great! I should merge #79 first right?

**Comment by dstansby** [comment]
I don't think it matters which order they go in.

**Comment by dstansby** [comment]
To save myself the hassle of downloading the database again and again I've rebased this on top of #79, so that should probalby now be merged first.

**Comment by wtbarnes** [comment]
I rebased out the commits from #79 and made changed the check for the ascii database fixture to check a separate variable in the rc file, `test_ascii_dbase_root` (the naming of all of these variables should probably be revisited 😅 ). That way, your "production" database and the one that you're testing against don't collide. Otherwise, if you were using a version other than 8.0.7, the tests would then all fail because the hashes are for that specific version.

**Pull request merged**
